### PR TITLE
Add to_userdata_typed implementation

### PR DESCRIPTION
**Pull request by DenisKolodin**
I've implemented `to_userdata_typed`. Also I've checked it and use in my project now. Works fine.

### CODE REVIEW

**Comment by jcmoyer** [comment]
If I am not mistaken, these two functions are identical due to null pointer optimization.

**Comment by DenisKolodin** [comment]
Yes, in most cases. But semantically they are different. When I use `Option`'s methods I take segfaults.

**Comment by jcmoyer** [comment]
Can you elaborate? The only information I can find on the matter is http://doc.rust-lang.org/book/ffi.html#the-nullable-pointer-optimization which doesn't mention any differences.

**Comment by DenisKolodin** [comment]
I've check it again and can't reproduce it with small example, sorry.
Null-pointer optimization is defined behaviour. I think we really have to use old version. I'll close this PR.

P.S. We use a lot of context switching and deep structs in our project... Maybe my version produces less optimized code so bug disappeared.

**Pull request closed without merging**
