### PR TITLE
Download lua 5.3, build it, use it's headers and its static library.

### PR DESCRIPTION
**Pull request by SirVer**
Followup to https://github.com/jcmoyer/rust-lua53/pull/3.

This branch is not cleaned up, but that works on mac os and on linux and guarantees that the correct libraries are used. It is also not terribly slow since cargo is clever about when to run prebuild.

Having a solution that works without hassle when the library is used as a dependency is pretty important IMHO. People are used that adding a crate in their dependency is all they need to do. I think this approach is the most compatible one. What do you think?

[Review on Reviewable](https://reviewable.io/reviews/jcmoyer/rust-lua53/5)

### CODE REVIEW

**Comment by jcmoyer** [comment]
I agree, having everything self-contained is preferable for cargo. But I think there should be an option to use a dynamic library (at least on Windows) so I want to take a closer look at this when I get some time.

**Comment by SirVer** [comment]
I am definitively broke windows support with my changes. I have no access to a windows machine to add it back in. I can confirm that the current solution works on mac os and linux, independent of system installs though. 

I'll use this branch for my projects going forward. Happy to clean it up a bit if you like the approach and want to merge it.

**Comment by jcmoyer** [comment]
Yeah, if you'd like to clean it up I can add windows support back in and merge it. Just let me know when it's OK to merge.

**Comment by SirVer** [comment]
Okay, branch cleaned up and rebased on master.

**Comment by jcmoyer** [comment]
Many thanks!

**Pull request merged**
