### PR TITLE
Add methods to work with extra space of state

### PR DESCRIPTION
**Pull request by DenisKolodin**
This PR implemets cool feature to work with an extra space of `State`.

It helps to attach and get fast access to own long-lived data through calls.

### CODE REVIEW

**Comment by SpaceManiac** [comment]
While I acknowledge the usefulness of exposing this feature, I think this wrapper is too thin. Calling `attach_extra` multiple times leaks memory, calling `detach_extra` multiple times or with the wrong type will break, calling `get_extra` with the wrong type will break. Indeed memory is leaked no matter what, because the `Box` is not dropped when the state is destroyed. Perhaps using `Box<Any + 'static + Send>` would be more appropriate?

It should also be noted that threads get a copy of the main thread's extra space when they are created, so even if null checks are added, `detach_extra` might be called on one thread and then another and double-free.

**Comment by DenisKolodin** [comment]
I'm agree with you. This feature is enough dangerous now. But I've taken a risk and use it, and found It's very fruitful. Let's try to improve API to make it more safe.

I was thinking about is uncontrolled access you mention. Some ideas to improve it:

1. Use `Option<T>` to return extra by value or reference to extra. It prevents to detach "nothing".
2. Drop any old extra if new attached
3. Drop extra when `State` is dropping
4. What about initial value of extra? It's undefined. We also can reset extra to null when `new` calling
5. Reset extra to null when `new_thread` created

It was about safe access to memory.

The follwing is about type safety:

```rust
pub struct State<T> {
  _marker: PhantomData<T>,
}

impl<T> State<T> {
  pub fn attach_extra<T>(...) { ... }
  pub fn from_pointer(...) -> State<T> { ... }
  pub fn new_thread<N>(...) -> State<N> { ... }
}
```

But it don't solve the problem fully, because we can restore it from pointer with any type bounded.

@SpaceManiac What do you thin about all this API's improvements?

Also, could you explain the idea about `Box<Any + 'static + Send>`?
My understanding it is:
1. `Any` helps us to downcat the type and take type id dynamically
2. `'static` means our type never lives less than State, right?
3. `Send` exists because State implements `Send`

Indeed we have to declare:
```rust
unsafe impl<T: Send> Send for State<T>;
```

It looks like enough plan, doesn't it? But I doubt about some backward-incompatible API's changing.

**Comment by DenisKolodin** [comment]
@SpaceManiac Done. It works more powerful and safe. Thank you for ideas! There is no back-incompatible changes.

**Comment by SpaceManiac** [comment]
Yes! I think I like this API. I'll review the implementation when I have a chance.

**Comment by SpaceManiac** [comment]
I propose combining `attach_extra` and `detach_extra` into one method with the signature `pub fn set_extra(&mut self, extra: Option<Extra>) -> Option<Extra>`, that both sets the extra data and returns the old one. I'm also a little unsure about `get_extra` returning `Option<&mut Extra>`, namely in that it exposes the `&mut Box`. I haven't thought of a way this could be abused to unsafety yet, but it seems unclean, like maybe `Option<&mut Any + 'static + Send>` would be the better choice.

**Comment by DenisKolodin** [comment]
The idea to unify extra data modification is reasonable. Сonsequently I've found a bug when attach data twice memory leaks. :+1: The new I like more: simpler and prettier.

But `get_extra` has no changes. I have to dereference twice to take something under box, but box reference becomes transient and don't pass checker. Also, I have to check extra is not null, to take the box inside `get_extra`. The last duplicates checking. What do you think about it?

**Comment by SpaceManiac** [comment]
I opened https://github.com/DenisKolodin/rust-lua53/pull/1 against this PR's branch with my proposed changes, mainly being tidying to set_extra, and changing get_extra to not return a `Box`. If you approve, merge that PR, and the changes will appear on this PR. I also avoided some `mem::transmute` calls that were ultimately unnecessary. I still want to do thorough testing to be certain the drop behavior is correct, but my reading of the code is that it is.

**Comment by DenisKolodin** [comment]
I like your changes: `null_mut` and `replace` make code more tidy and clear. I've merged that and checked with my project. All tests were passed. :+1: 

One thing we haven't discussed yet: extra space intialization with null when new state created. For threads it's absolutely necessary. But we can skip that if lua does it already, but I didn't find any initialization of this field there: [lua/src/lstate.c#L295](https://github.com/lua/lua/blob/ef91579f913d6e1c4666d10b3dc08e1da247328a/src/lstate.c#L295)
I can't believe that lua leaves it untouched, but I take `Some(segfault)` if skip setting extra space to null. May lua have a compilation option to clear extra space at new creation?

**Comment by SpaceManiac** [comment]
I think it's really the case that we must initialize the extra space ourselves.

**Comment by DenisKolodin** [comment]
That's true! We made it a little safer.

**Comment by jcmoyer** [comment]
Originally I believe that the rationale for not wrapping this function is because you can just store whatever extra information you need in a struct along with the Lua state, e.g.
```rust
struct StateWithData {
  state: lua::State
  foo: i32,
  bar: i32
}
```
Are there use cases where this is inadequate?

**Comment by DenisKolodin** [comment]
It's necessary to get an extra in a context where data composition is unavailable, like this:
```rust
unsafe extern "C" fn lua_call_me(L: *mut lua_State) -> c_int {
  // Get data, attached to state
}
```

Registry is also available here, but by string keys only.

**Comment by jcmoyer** [comment]
Fair enough, I'll go ahead and merge this. Thanks.

**Pull request merged**
