### PR TITLE
Mark ThreadStatus must_use and simplify from_c_int

### PR DESCRIPTION
**Pull request by SpaceManiac**
Adding `#[must_use]` to `ThreadStatus` means that if the result of a method that returns it is ignored, a warning is printed, much like if a `std::result::Result` is unused.

The change to `from_c_int` is to simplify all the `.unwrap()` calls and provide a more descriptive panic message.

### CODE REVIEW

**Comment by DenisKolodin** [comment]
I like it! And what about to use `Result<Success, Error>` and split `ThreadStatus` to both:
```rust
pub enum Success {
    Ok,
    Yield,
}

pub enum Error {
    RuntimeError,
    SyntaxError,
    // ...
}
```
It makes possible to use standard error handling features: `try!`, `From<Error>`, etc.

**Comment by SpaceManiac** [comment]
I like it, but I think it requires more drastic changes, e.g. to be able to return `Result` from callback functions, to be truly useful.

**Comment by jcmoyer** [comment]
I like the concept of panicking instead of returning None, but is there a good case to be made for requiring people to use the ThreadResult?

**Comment by SpaceManiac** [comment]
It is the same case as for requiring people to use Result from the standard library: that usually, users do not intend to disregard errors generated by functions they call, so they must go to a little effort to do so. I should note that this attribute only generates warnings (not errors) by default, which can be easily silenced.

Panicking instead of returning None is mostly for internal tidyness; everywhere from_c_int is called, it is immediately unwrapped anyways.

**Comment by jcmoyer** [comment]
Makes sense, thanks for the PR.

**Pull request merged**
