### PR TITLE
Support building and linking against a local Lua source tarball.

### PR DESCRIPTION
**Pull request by cjcole**

### CODE REVIEW

**Comment by cjcole** [comment]
Just saw pull request #32. If you think you'll take this one I'll rebase it after #32 goes in.

**Comment by SpaceManiac** [comment]
Just a suggestion, but it might be useful to allow for the file to be named something other than `lua-5.3.0.tar.gz` exactly.

**Comment by cjcole** [comment]
Sure, why not?

**Comment by jcmoyer** [comment]
Yeah I think it makes more sense to use `lua_source_path` as the path to untar. Other than that looks fine, it just needs a rebase.

**Pull request closed without merging**
